name: Sync with upstream

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        ref: vial
        fetch-tags: latest

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: vial
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: vial
        upstream_sync_repo: ergohaven/vial-qmk

        test_mode: ${{ inputs.sync_test_mode }}

    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."

    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."

    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
